#!/bin/bash

echo "=== DNS Configuration Fix for app.viralsplit.io ==="
echo ""
echo "Current Status:"
echo "- api.viralsplit.io: ✅ Working (Cloudflare → Railway)"
echo "- app.viralsplit.io: ❌ Not working (misconfigured)"
echo ""
echo "Issue: app.viralsplit.io points to Vercel IP but isn't properly configured"
echo ""
echo "=== SOLUTION ==="
echo ""
echo "Since you're using Cloudflare for DNS, you need to:"
echo ""
echo "1. In Cloudflare Dashboard:"
echo "   - Delete the current A record for app.viralsplit.io (64.29.17.131)"
echo "   - Add a CNAME record:"
echo "     • Name: app"
echo "     • Target: cname.vercel-dns.com"
echo "     • Proxy: OFF (DNS only - gray cloud)"
echo ""
echo "2. In Vercel Dashboard:"
echo "   - Go to your viralsplit project settings"
echo "   - Go to Domains tab"
echo "   - Make sure app.viralsplit.io is added"
echo "   - It should show as 'Valid Configuration' once DNS propagates"
echo ""
echo "3. Alternative - Use the latest deployment URL directly:"
echo "   Your latest working deployment is:"
echo "   https://viralsplit-sg0vqazb4-infos-projects-08e74b74.vercel.app"
echo ""
echo "=== Verification Commands ==="
echo ""
echo "Check current DNS:"
echo "dig app.viralsplit.io"
echo ""
echo "Test API connection:"
echo "curl https://api.viralsplit.io/health"
echo ""
echo "After DNS change (wait 5-10 minutes for propagation):"
echo "curl -I https://app.viralsplit.io"