services:
  # API Service
  - type: web
    name: viralsplit-api
    env: python
    plan: free
    buildCommand: pip install -r apps/api/requirements.txt
    startCommand: cd apps/api && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_EXPIRATION_HOURS
        value: 24
      - key: CLOUDFLARE_ACCOUNT_ID
        sync: false
      - key: CLOUDFLARE_ACCESS_KEY_ID
        sync: false
      - key: CLOUDFLARE_SECRET_ACCESS_KEY
        sync: false
      - key: CDN_DOMAIN
        value: cdn.viralsplit.io
      - key: R2_BUCKET_NAME
        value: viralsplit-media
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: LEMONSQUEEZY_API_KEY
        sync: false
      - key: LEMONSQUEEZY_WEBHOOK_SECRET
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: viralsplit-redis
          property: connectionString
      - key: DEBUG
        value: false
      - key: ENVIRONMENT
        value: production

  # Redis Service
  - type: redis
    name: viralsplit-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
