#!/bin/bash

echo "=== Fixing app.viralsplit.io DNS Configuration ==="
echo ""
echo "Current Issue:"
echo "- app.viralsplit.io points to A record 64.29.17.131"
echo "- Connection is being reset by peer"
echo "- Vercel has valid SSL cert but connection fails"
echo ""
echo "=== CLOUDFLARE DNS FIX ==="
echo ""
echo "You need to change the DNS record in Cloudflare Dashboard:"
echo ""
echo "1. Login to Cloudflare Dashboard"
echo "2. Select viralsplit.io domain"
echo "3. Go to DNS -> Records"
echo "4. Find the 'app' record (currently A record to 64.29.17.131)"
echo "5. EDIT the record:"
echo "   - Change Type from 'A' to 'CNAME'"
echo "   - Change Target from '64.29.17.131' to 'cname.vercel-dns.com'"
echo "   - IMPORTANT: Set Proxy Status to 'DNS only' (gray cloud ☁️)"
echo "   - Keep TTL as Auto"
echo "6. Save the record"
echo ""
echo "=== Alternative Method (CLI) ==="
echo ""
echo "If you have Cloudflare CLI (wrangler) installed:"
echo ""
echo "# Delete A record"
echo "wrangler dns record delete viralsplit.io --name app --type A"
echo ""
echo "# Add CNAME record"
echo "wrangler dns record create viralsplit.io --name app --type CNAME --content cname.vercel-dns.com --proxied false"
echo ""
echo "=== Verification ==="
echo ""
echo "After making the change, wait 2-5 minutes and test:"
echo ""
echo "# Check DNS propagation"
echo "dig app.viralsplit.io CNAME +short"
echo "# Should show: cname.vercel-dns.com"
echo ""
echo "# Test connection"
echo "curl -I https://app.viralsplit.io"
echo "# Should return HTTP 200 OK"
echo ""
echo "=== Why This Fixes It ==="
echo ""
echo "1. A records point directly to IP addresses"
echo "2. Vercel's edge network uses different IPs for different regions"  
echo "3. CNAME records point to hostnames that Vercel can manage dynamically"
echo "4. Vercel can then route traffic properly and serve the correct SSL cert"
echo ""
echo "Your API works because api.viralsplit.io correctly uses Cloudflare proxy"
echo "Your frontend needs DNS-only CNAME to let Vercel handle the routing"